// http://nodejs.cn/api/process.html#process_process_env
const {
  env
} = process;
console.log(env);

/*
{ GIT_PS1_SHOWDIRTYSTATE: '1',
  TERM_PROGRAM: 'vscode',
  rvm_bin_path: '/Users/wgy/.rvm/bin',
  VIRTUALENVWRAPPER_SCRIPT: '/usr/local/bin/virtualenvwrapper.sh',
  VIRTUALENVWRAPPER_PROJECT_FILENAME: '.project',
  NVM_CD_FLAGS: '',
  GEM_HOME: '/Users/wgy/.rvm/gems/ruby-2.3.0',
  TERM: 'xterm-256color',
  SHELL: '/bin/bash',
  IRBRC: '/Users/wgy/.rvm/rubies/ruby-2.3.0/.irbrc',
  TMPDIR: '/var/folders/p8/qshb5bzn4vvfk0rh5w809s5m0000gn/T/',
  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.RcnoK9ZZCm/Render',
  TERM_PROGRAM_VERSION: '1.21.1',
  OLDPWD: '/Users/wgy/internet/github/my-github/node-note/note/NodeAPI',
  MY_RUBY_HOME: '/Users/wgy/.rvm/rubies/ruby-2.3.0',
  NVM_DIR: '/Users/wgy/.nvm',
  USER: 'wgy',
  _system_type: 'Darwin',
  rvm_path: '/Users/wgy/.rvm',
  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.rJEroxuiRc/Listeners',
  __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',
  WORKON_HOME: '/Users/wgy/workspaces',
  rvm_prefix: '/Users/wgy',
  PATH: '/Users/wgy/.rvm/gems/ruby-2.3.0/bin:/Users/wgy/.rvm/gems/ruby-2.3.0@global/bin:/Users/wgy/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/Users/wgy/.rvm/gems/ruby-2.3.0/bin:/Users/wgy/.rvm/gems/ruby-2.3.0@global/bin:/Users/wgy/.rvm/rubies/ruby-2.3.0/bin:/Users/wgy/.nvm/versions/node/v8.9.3/bin:/Users/wgy/java/maven/apache-maven-3.5.2/bin:/Users/wgy/.rvm/bin:/Users/wgy/java/maven/apache-maven-3.5.2/bin',
  VIRTUALENVWRAPPER_HOOK_DIR: '/Users/wgy/workspaces',
  PWD: '/Users/wgy/internet/github/my-github/node-note/note/NodeAPI/03_process',
  JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home',
  LANG: 'zh_CN.UTF-8',
  _system_arch: 'x86_64',
  XPC_FLAGS: '0x0',
  PS1: '\\[\\033[0;35m\\]\\u\\[\\033[0;32m\\]$(__git_ps1)\\[\\033[0;34m\\] \\W $ \\[\\033[0m\\]',
  _system_version: '10.12',
  XPC_SERVICE_NAME: '0',
  rvm_version: '1.29.3 (latest)',
  SHLVL: '2',
  M2_HOME: '/Users/wgy/java/maven/apache-maven-3.5.2',
  HOME: '/Users/wgy',
  VSCODE_NLS_CONFIG: '{"locale":"zh-cn","availableLanguages":{"*":"zh-cn"}}',
  LOGNAME: 'wgy',
  GEM_PATH: '/Users/wgy/.rvm/gems/ruby-2.3.0:/Users/wgy/.rvm/gems/ruby-2.3.0@global',
  VSCODE_IPC_HOOK: '/Users/wgy/Library/Application Support/Code/1.21.1-main.sock',
  VSCODE_NODE_CACHED_DATA_DIR_1305: '/Users/wgy/Library/Application Support/Code/CachedData/79b44aa704ce542d8ca4a3cc44cfca566e7720f1',
  NVM_BIN: '/Users/wgy/.nvm/versions/node/v8.9.3/bin',
  VIRTUALENVWRAPPER_WORKON_CD: '1',
  VSCODE_PID: '1305',
  RUBY_VERSION: 'ruby-2.3.0',
  _system_name: 'OSX',
  _: '/Users/wgy/.nvm/versions/node/v8.9.3/bin/node' }
*/
